import type { BuybackTimeframe } from "./types";

export const TIMEFRAME_OPTIONS: {
  value: BuybackTimeframe;
  label: string;
  description: string;
  icon: string;
}[] = [
  {
    value: "instant",
    label: "Instant",
    description: "Buyback triggers as soon as revenue accumulates",
    icon: "⚡",
  },
  {
    value: "hourly",
    label: "Every Hour",
    description: "Buybacks execute once per hour",
    icon: "🕐",
  },
  {
    value: "daily",
    label: "Daily",
    description: "Buybacks execute once every 24 hours",
    icon: "📅",
  },
  {
    value: "weekly",
    label: "Weekly",
    description: "Buybacks execute once per week — larger, impactful burns",
    icon: "🗓️",
  },
];

export const MOCK_TOKENS = [
  {
    id: "1",
    mint: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
    name: "SafeMoon V3",
    ticker: "SFM3",
    description: "Fully automated buyback & burn. 100% of trading fees returned to holders.",
    imageUrl: null,
    creatorWallet: "FLMb...PJkw",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    buybackRate: 100,
    buybackTimeframe: "instant" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    marketCap: 66200,
    price: 0.0000662,
    priceChange24h: 1665.6,
    volume24h: 14600,
    revenue: 1400,
    buybacksCompleted: 0,
    buybacksPending: 1400,
    totalBurned: 0,
    bondingCurveProgress: 100,
  },
  {
    id: "2",
    mint: "9YQqMktYkNRBxJUxGzfxCrNnUpGZpqcNxfmzBPMaVjhT",
    name: "BurnKing",
    ticker: "BKING",
    description: "Weekly mega-burns. Every Friday all accumulated fees go to buyback.",
    imageUrl: null,
    creatorWallet: "4Bx7...mNpQ",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    buybackRate: 75,
    buybackTimeframe: "weekly" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    marketCap: 124000,
    price: 0.000124,
    priceChange24h: 342.1,
    volume24h: 28900,
    revenue: 3200,
    buybacksCompleted: 2100,
    buybacksPending: 1100,
    totalBurned: 2100,
    bondingCurveProgress: 78,
  },
  {
    id: "3",
    mint: "3mZhkCpKVLjRTbLUsFJUFqgNqVwpSMHEU2rV7xrMYdGh",
    name: "DailyBurn",
    ticker: "DBURN",
    description: "Every 24 hours, fees automatically buy back and burn tokens.",
    imageUrl: null,
    creatorWallet: "9Kp2...rQwE",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    buybackRate: 50,
    buybackTimeframe: "daily" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    marketCap: 892000,
    price: 0.000892,
    priceChange24h: 88.5,
    volume24h: 145000,
    revenue: 18400,
    buybacksCompleted: 12100,
    buybacksPending: 6300,
    totalBurned: 12100,
    bondingCurveProgress: 45,
  },
];
