import type { BuybackTimeframe } from "./types";

export const TIMEFRAME_OPTIONS: {
  value: BuybackTimeframe;
  label: string;
  description: string;
}[] = [
  { value: "5m",  label: "Every 5 min",  description: "High-frequency burns, maximum deflationary pressure" },
  { value: "15m", label: "Every 15 min", description: "Frequent execution with meaningful batch sizes" },
  { value: "30m", label: "Every 30 min", description: "Balanced — consistent burns every half hour" },
  { value: "1h",  label: "Hourly",       description: "One large hourly burn, visible on-chain activity" },
];

export function seedColour(name: string) {
  const palettes = [
    { bg: "#0a1a12", border: "#173324", text: "#00ff94" },
    { bg: "#13101f", border: "#221a38", text: "#a78bfa" },
    { bg: "#1a0d0d", border: "#331414", text: "#f87171" },
    { bg: "#0d1520", border: "#182438", text: "#60a5fa" },
    { bg: "#1a1208", border: "#332413", text: "#fbbf24" },
    { bg: "#111118", border: "#1e1e28", text: "#e8e8e8" },
  ];
  return palettes[name.charCodeAt(0) % palettes.length];
}

export const MOCK_TOKENS = [
  {
    id: "1",
    mint: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
    name: "SafeMoon V3",
    ticker: "SFM3",
    description: "100% of all trading fees automatically buy back and permanently burn tokens. Settings locked forever on-chain.",
    imageUrl: null,
    creatorWallet: "FLMb...PJkw",
    creatorName: "mr.devvvv",
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
    twitter: "https://twitter.com/safemoon",
    telegram: "https://t.me/safemoon",
    website: null,
    buybackRate: 100,
    buybackTimeframe: "5m" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 45 * 60 * 1000),
    hasLP: false,
    lpSolAmount: 0,
    marketCap: 66200,
    price: 0.0000662,
    priceChange24h: 1665.6,
    volume24h: 14600,
    revenue: 1400,
    buybacksCompleted: 0,
    buybacksPending: 1400,
    totalBurned: 0,
    replies: 47,
    bondingCurveProgress: 100,
  },
  {
    id: "2",
    mint: "9YQqMktYkNRBxJUxGzfxCrNnUpGZpqcNxfmzBPMaVjhT",
    name: "BurnKing",
    ticker: "BKING",
    description: "Hourly mega-burns. Every 60 minutes all accumulated protocol fees execute a massive buyback.",
    imageUrl: null,
    creatorName: "burnking_sol",
    creatorWallet: "4Bx7...mNpQ",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    twitter: null,
    telegram: "https://t.me/burnking",
    website: "https://burnking.io",
    buybackRate: 75,
    buybackTimeframe: "1h" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    hasLP: true,
    lpSolAmount: 5,
    marketCap: 124000,
    price: 0.000124,
    priceChange24h: 342.1,
    volume24h: 28900,
    revenue: 3200,
    buybacksCompleted: 2100,
    buybacksPending: 1100,
    totalBurned: 2100,
    replies: 112,
    bondingCurveProgress: 78,
  },
  {
    id: "3",
    mint: "3mZhkCpKVLjRTbLUsFJUFqgNqVwpSMHEU2rV7xrMYdGh",
    name: "DailyBurn",
    ticker: "DBURN",
    description: "Every 30 minutes, fees automatically buy back and burn tokens. Simple, predictable, permanent.",
    imageUrl: null,
    creatorName: "0xdaily",
    creatorWallet: "9Kp2...rQwE",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    twitter: "https://twitter.com/dailyburn",
    telegram: null,
    website: null,
    buybackRate: 50,
    buybackTimeframe: "30m" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    hasLP: true,
    lpSolAmount: 10,
    marketCap: 892000,
    price: 0.000892,
    priceChange24h: 88.5,
    volume24h: 145000,
    revenue: 18400,
    buybacksCompleted: 12100,
    buybacksPending: 6300,
    totalBurned: 12100,
    replies: 284,
    bondingCurveProgress: 45,
  },
  {
    id: "4",
    mint: "5tRpK2vNmJfXYA8hCqLzW1uGsVbDe3FgMnKoP6jQrHsU",
    name: "QuickFire",
    ticker: "QFIRE",
    description: "Every 5 minutes the agent wakes and burns. Constant deflationary pressure. Maximum aggression.",
    imageUrl: null,
    creatorName: "firelord",
    creatorWallet: "7Wx9...zLpK",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    twitter: "https://twitter.com/quickfire",
    telegram: "https://t.me/quickfire",
    website: "https://quickfire.xyz",
    buybackRate: 80,
    buybackTimeframe: "5m" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    hasLP: false,
    lpSolAmount: 0,
    marketCap: 38500,
    price: 0.0000385,
    priceChange24h: 215.3,
    volume24h: 9200,
    revenue: 920,
    buybacksCompleted: 720,
    buybacksPending: 200,
    totalBurned: 720,
    replies: 33,
    bondingCurveProgress: 22,
  },
  {
    id: "5",
    mint: "8nPqLmWrUvCxD9aEtGfBjYkZsAeN2iHoV7cSdQpMrXtK",
    name: "MaxBurn",
    ticker: "MBURN",
    description: "100% of fees. 5-minute execution. The most aggressive buyback & burn protocol on pump.fun.",
    imageUrl: null,
    creatorName: "maxburn_dev",
    creatorWallet: "2Nt4...hVqS",
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    twitter: "https://twitter.com/maxburn",
    telegram: null,
    website: null,
    buybackRate: 100,
    buybackTimeframe: "5m" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 30 * 60 * 1000),
    hasLP: false,
    lpSolAmount: 0,
    marketCap: 12800,
    price: 0.0000128,
    priceChange24h: 4420.0,
    volume24h: 5100,
    revenue: 510,
    buybacksCompleted: 0,
    buybacksPending: 510,
    totalBurned: 0,
    replies: 8,
    bondingCurveProgress: 8,
  },
  {
    id: "6",
    mint: "6kSqBpUfNvLxJaYmCgWdRtGnEiAzKpVoDcMhXsQeZrWb",
    name: "TrustBurn",
    ticker: "TBURN",
    description: "75% every 15 minutes. The community knows exactly when burns happen. Maximum transparency.",
    imageUrl: null,
    creatorName: "trustburn",
    creatorWallet: "5Mk7...yCnL",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    twitter: "https://twitter.com/trustburn",
    telegram: "https://t.me/trustburn",
    website: "https://trustburn.finance",
    buybackRate: 75,
    buybackTimeframe: "15m" as BuybackTimeframe,
    buybackLocked: true,
    buybackLockedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    hasLP: true,
    lpSolAmount: 3,
    marketCap: 445000,
    price: 0.000445,
    priceChange24h: 156.8,
    volume24h: 67000,
    revenue: 8900,
    buybacksCompleted: 6700,
    buybacksPending: 2200,
    totalBurned: 6700,
    replies: 198,
    bondingCurveProgress: 62,
  },
];
